/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const FETCHED_VIRTUAL_SERVERS = 'FETCHED_VIRTUAL_SERVERS';

export const FETCHED_SERVER_FARMS = 'FETCHED_SERVER_FARMS';

export const FETCHED_REAL_SERVERS = 'FETCHED_REAL_SERVERS';

export const FETCHED_DASHBOARD = 'FETCHED_DASHBOARD';

export const SEARCH_DOMAIN_DONE = 'SEARCH_DOMAIN_DONE';

export const FETCHED_FC_SITES = 'FETCHED_FC_SITES';

export const FETCHED_FC_CLUSTERS = 'FETCHED_FC_CLUSTERS';

export const FETCHED_FC_CLUSTER = 'FETCHED_FC_CLUSTER';

export const FETCHED_FC_COMPUTER_RESOURCE = 'FETCHED_FC_COMPUTER_RESOURCE';

export const FETCHED_FC_CLUSTER_HOSTS = 'FETCHED_FC_CLUSTER_HOSTS';

export const FETCHED_FC_HOST_VMS = 'FETCHED_FC_HOST_VMS';

export const FETCHED_FC_HOST = 'FETCHED_FC_HOST';

export const FETCHED_FC_VM = 'FETCHED_FC_VM';
